### ISSUE TITLE
Why here is negative MCM score？

### ISSUE THREAD

**Issue by LuFan31** [deeplearning-wisc/MCM#14]
Hi, thank you for your excellent work. But I have a question when reproducing the code. Why is a negative MCM score used in Line.248 in [MCM/utils/detection_util.py](https://github.com/deeplearning-wisc/MCM/blob/main/utils/detection_util.py)? According to convention, ID samples should have higher scores, and ID samples obtain higher multimodal similarity in the CLIP model. Therefore, shouldn't we not use the negative sign here?
![image](https://github.com/deeplearning-wisc/MCM/assets/88334335/5a1ecebb-7480-4cdf-bb43-a676446ce745)

**Comment by alvinmingsf** [comment]
Thanks for your interest in our work! This is because in L259 in [detection_util.py](https://github.com/deeplearning-wisc/MCM/blob/main/utils/detection_util.py), the function takes in -in_score, -out_score as inputs. So if you implement in a way that removes negative signs in both places, it should also work. 
```python
aurocs, auprs, fprs = [], [], []
measures = get_measures(-in_score, -out_score)
```

**Comment by LuFan31** [comment]
Thanks for your apply!
